### ISSUE TITLE
[crash] querying sibling model: failure to set Id value

### ISSUE THREAD

**Issue by tunjifw** [vapor/fluent-kit#150]
<img width="477" alt="Screen Shot 2020-02-09 at 2 40 54 AM" src="https://user-images.githubusercontent.com/10441984/74098442-362be000-4ae6-11ea-9665-3e1ea3d236e1.png">

<img width="769" alt="Screen Shot 2020-02-09 at 2 48 26 AM" src="https://user-images.githubusercontent.com/10441984/74098487-ae92a100-4ae6-11ea-8170-33f70a91915c.png">

<img width="1077" alt="Screen Shot 2020-02-09 at 2 44 30 AM" src="https://user-images.githubusercontent.com/10441984/74098465-6b383280-4ae6-11ea-8fa7-a3bc37d00c66.png">

<img width="1079" alt="Screen Shot 2020-02-09 at 2 42 43 AM" src="https://user-images.githubusercontent.com/10441984/74098453-552a7200-4ae6-11ea-8d22-e50257d54edd.png">

**Comment by tanner0101** [comment]
This is happening since `Room` was not fetched from the database. The `idValue` on siblings is set when decoding the value from database output. I'm not exactly sure what the `exampleHandler` is attempting to do. Is this a PATCH or PUT request? If it is, you should use the Room ID from the URL to fetch the Room from the database first, then you can query the relations.

**Comment by tunjifw** [comment]
@tanner0101 ahhh yea you're right..rookie mistake. Didn't query the DB first to fetch the room. Fell back into my old v3 ways..closing this issue..
