### ISSUE TITLE
Storing a nested object in the database.

### ISSUE THREAD

**Issue by ttrznadel** [vapor/fluent-kit#369]
What happened to:
`@CompoundField` and `@NestedField` ?
https://github.com/vapor/fluent-kit/pull/170

How to get this behavior on current version?
I would be grateful for an example.

**Comment by tanner0101** [comment]
Hi @ttrznadel. `@CompoundField` was renamed to `@Group`. `@NestedField` was removed due to some issues discovered with its implementation. There is currently an issue open here to solve those issues and re-add it: https://github.com/vapor/fluent-kit/issues/294

More information on using `@Group` can be found here: https://docs.vapor.codes/4.0/fluent/model/#group

Let me know if you have any more questions, thanks!
