### ISSUE TITLE
Discussion: Why the Model in Fluent 4.0 does not conform to struct?

### ISSUE THREAD

**Issue by mauliknshah** [vapor/fluent-kit#386]
In a recent assignment given to me, I was given a task to compare the performance of `class` vs `struct` with `Model` protocol in the Fluent 4.0. Surprisingly, I found out that the `struct` cannot conform to `Model` anymore, and protocols like `Fields` and `AnyProperty` are made class-only protocols. 

Are there any specific technical reasons, why the development team decided against allowing `Model` to conform to `struct`?

**Comment by 0xTim** [comment]
From Discord:

> I hope async/await will let Fluent re-adopt structs. The main issue is that futures (or escaping callbacks general) make it impossible to use mutating or inout which are key to making value types usable in Swift.
For example, since model.save() is async, and thus can't be mutating, the method would need to return the updated model struct.
That doesn't feel right in Swift. It should be a mutating method.
Re: @0xTim's middleware example, the model should be passed inout to avoid copying. But again, the middleware method is async so not possible.

**Comment by hyouuu** [comment]
Thanks for the explanation! Just wondering with the async/await here, is it possible now? @0xTim

**Comment by 0xTim** [comment]
@hyouuu No async/await doesn't change anything
