### ISSUE TITLE
Field<Value> as property wrapper?

### ISSUE THREAD

**Issue by zdnk** [vapor/fluent-kit#42]
Would it be possible and more friendly to implement fields as property wrappers and also possibly get rid of wrapping every model in `Row<>`?

**Comment by linqingmo** [comment]
maybe you can try property-wrapper branch?

**Comment by zdnk** [comment]
I see. Cool. Looking forward to the final solution :)

**Comment by tanner0101** [comment]
I definitely want to use property wrappers for `Field`, but as the proposal currently stands, the access level limitations will make this difficult. I've written a response that explains why I think this should be changed so that FluentKit can make use of property wrappers:
https://forums.swift.org/t/se-0258-property-wrappers-second-review/25843/14?u=tanner0101

It seems like my response may have been successful, but we still have to wait and see. Any support you could give to my post there would be appreciated!

**Comment by tanner0101** [comment]
This was added in #54 :)
