### ISSUE TITLE
Does Vapor Fluent support filtering by distance in MongoDB?

### ISSUE THREAD

**Issue by Linkadi98** [vapor/fluent-kit#423]
As my experiences with Vapor Fluent, Fluent Filter is very generic and powerful for several kind of databases. But there are some cases Fluent filter, somehow, does not support with specific database.

As my question above, I can make a query to filter the distance to a coordinate easily by using aggregate in MongoKitten, but it will be easier and more convinient if Fluent filter also supports this kind of filter. I build a complex group of queries and distance filter query is a part of it.

If Fluent supports this, please show me how to make that query.

Thanks

**Comment by madsodgaard** [comment]
@Linkadi98 The problem is that Fluent must be database agnostic, and the problem you're trying to solve is very specific to a specific database. With Postgres for example you need something like `PostGIS` to make this work, which Fluent cannot assume you have access to. I am not sure about `MongoKitten`, but with `FluentSQL` helpers you can add raw SQL filters directly to a Fluent query:

```swift
let username = "mads"

User
  .query(on: req.db)
  .filter(.sql(embed: "username = LOWER(\(bind: username))"))
  ...
```

**Comment by Linkadi98** [comment]
MongoKitten comes with Vapor, but I can see that a custom query like my question is not built in Fluent. Have to implement myself.

Thanks for your help @madsodgaard
