### ISSUE TITLE
Eager-loading with pagination?

### ISSUE THREAD

**Issue by Linkadi98** [vapor/fluent-kit#424]
Hi, I'm working on this issue. When I make a query with `with()` function to get the children of model, I realize that all the children will be get with `all()` function, if there are many children, then the query will get all of them, that can be a heavy job.

So should eager-loading supports pagination or chunk or limit,...? If it does, how do I implement that? Or there could be other solutions for this?

Thank you,

**Comment by 0xTim** [comment]
This is a complex question with no good answer unfortunately. In general, no children should not be pagination as well, because it gets complex to pass through page numbers and counts to just the children instead of the parent.

IMO you should only eager load children during pagination if you're confident there aren't going to be more than you can cope with. If you're at the stage where you want to paginate the relationships as well, then you should probably not be eager loading the relationships and it should be up to the client to manually fetch the models from the relationships it needs

**Comment by Linkadi98** [comment]
Yes, the hard part is passing through page numbers and counts to just the children. I wish I cound have just one request to get the children with pagination, but for now I have to do like your suggestion.

**Comment by 0xTim** [comment]
It is possible to do it on one request, you'll just need to do everything manually. The eager loading makes another request to get the required relationships so you can make this request manually passing in an offset and count which you pull from custom query values for each relationship etc
