### ISSUE TITLE
Cannot update value of an @OptionalEnum field to nil

### ISSUE THREAD

**Issue by peterlondon1** [vapor/fluent-kit#444]
I attempt to update a field defined as an @OptionalEnum to **nil**. The field value does not change. Changing the value to other values of the enum **does** work correctly.

I have also seen this error with other optional fields, i.e. I can update the field to other values, but not to nil

I have shown this to Tim Condon who showed me how to see the error occurring in the debug log, shown below.

### To Reproduce

**FIELD DEFINITION:**	
	@OptionalEnum(key: "playerRequest")
	var playerRequest: PlayerRequestType?

**CODE TO SET OPTIONAL ENUM TO NIL:**
	sportPlayerPivotForPlayerOut.playerStatus = .notPlaying
	sportPlayerPivotForPlayerOut.playerRequestComments = "removed by organiser"
	**sportPlayerPivotForPlayerOut.playerRequest = nil**	//TIM??? !!!	not working
	sportPlayerPivotForPlayerOut.$currentLeague.id = nil
	sportPlayerPivotForPlayerOut.leagueNumber = nil
	let update2 = sportPlayerPivotForPlayerOut.update(on: req.db)
	updates.append(update2)

DEBUG TRACE SHOWING VALUE -NOT- UPDATED:

[ DEBUG ] query update sport_player_pivots filters=[sport_player_pivots[id] = 466EFFB4-8DD7-4812-A66F-29D048E20B49] input=[[playerStatus: notPlaying, dateModified: "2021-07-20T10:38:29Z", leagueNumber: nil, playerRequestComments: "removed by organiser", **playerRequest: remain**, currentLeagueID: nil]] [database-id: psql, request-id: 6BD2882E-DAB7-4985-A1A6-9803B4C59E3D] (FluentKit/Query/Builder/QueryBuilder.swift:297)

1. Add package with configuration '...'
2. Send request with options '...'
3. See error

### Expected behavior

Field value updated to nil

### Environment

Using **postgres**
framework: 4.48.0
toolbox: 18.3.2

* OS version:

11.4

**Comment by peterlondon1** [comment]
I tested this again today (just by chance) after updating all packages to latest. The bug still exists.

**Comment by gwynne** [comment]
@peterlondon1 Yikes, that's not good 😕. Can you double-check that the FluentKit you're building against is version `1.21.0`, just in case? If it is, let me know if the symptoms are still identical to what was originally reported when you opened the issue and I'll tackle it as quickly as I can. Hopefully we'll be able to devise a unit test that covers your case - I thought I'd gotten all the corners with the current set of tests, but it wouldn't surprise me to find out otherwise.... Fluent 5 is gonna have a nicer API for this sort of thing, I promise that much 😆

**Comment by peterlondon1** [comment]
Hi Gwynne,

I do apologise.

I definitely ran Xcode / File / Packages / Update to latest package versions on Feb 19th and it only pulled in FluentKit 1.20.0.

I just ran it again and it pulled in FluentKit 1.21.0 (and no other updates).

So maybe you just did the update? And — and it worked! Thanks so much. This bug has been around a long time and it seems a really bad bug for a Swift-related package - not being able to nil a conditional variable!

BTW How will Vapor 5 be different for “this sort of thing”? And what’s the timeline?!

Thanks a lot,

Peter

	@OptionalEnum(key: "playerRequest")
	var playerRequest: PlayerRequestType?

enum PlayerRequestType: String, Codable {
	case leave	//	player requested
	case remove	//	organiser mark
…
}

**Comment by gwynne** [comment]
No worries! You're right - I'd just done the update moments immediately before you'd posted (2 minutes, according to the timestamps 😆). The issue was closed out automatically when I merged the PR. I agree wholeheartedly about the ugliness of this bug and others like it, for sure - Fluent 4 has never really gotten all of the polish and attention it deserved, mostly as a result of bad luck and equally bad timing. That above anything else is what I hope to avoid for Fluent 5 - no tacking on multiple large features in the last RC, no skimping on test coverage, and so forth. And a significantly improved API that takes full advantage of all the new capabilities Swift's gained since 5.2, of course 🙂. There's a channel devoted to Fluent 5 discussion on our Discord server as well, if you're interested in finding out more and/or contributing to the early stages of the design process; believe me when I say any input you care to offer will be welcomed, I've been doing far too little talking about it there myself so far 😅.
