### ISSUE TITLE
Crash on getting a nil value

### ISSUE THREAD

**Issue by rafiki270** [vapor/fluent-kit#45]
![image](https://user-images.githubusercontent.com/218245/59849678-3eb98580-9360-11e9-8c4f-d5c121716d3c.png)

The value is `nil`
and model `public let nodeLabels = Field<String?>("node_labels")`
...
so it only happens if I don't set (even if it's nil) the value on the row after creating it with `.row()`??
So it looks like it crashes if the Row representation of the model value is not initialised?

**Comment by rafiki270** [comment]
So I understand this is not a bug but a limitation of the property wrappers. Either way, it took me a really long time to debug so I would suggest the error message tells you at least what model it caused and explain that all Row properties need to be initialised before use

**Comment by tanner0101** [comment]
@rafiki270 I've added a small flag in the latest version of the property wrappers implementation that will give a better error depending on whether the field has been loaded from database output, or if it is newly initialized:
https://github.com/vapor/fluent-kit/blob/property-wrapper-2/Sources/FluentKit/Properties/Field.swift#L26-L30

Furthermore, property wrappers should make the situation slightly better since you will have a single place that you initialize your models, where you can be sure to set all of the values:
https://github.com/vapor/fluent-kit/blob/property-wrapper-2/Sources/FluentKit/Migration/MigrationLog.swift#L15-L20

**Comment by tanner0101** [comment]
This is fixed now
