### ISSUE TITLE
Make `create(on:)` return the model instead of Void

### ISSUE THREAD

**Issue by davdroman** [vapor/fluent-kit#465]
I wanted to use `async let` to parallelize creating models within my function:

```swift
async let modelA = ModelA().create(on: req.db) // modelA is async Void :(
async let modelB = ModelB().create(on: req.db) // modelB is async Void :(
```

I tried to work around it like this:

```swift
let modelA = ModelA()
async let _ = modelA.create(on: req.db)
let modelB = ModelB()
async let _ = modelB.create(on: req.db)

doSomethingElse(with: [modelA, modelB]) // creation is not guaranteed at this point (see below)
```

This is subtly problematic, for these reasons:

- The bare models exist on their own, so their creation is not guaranteed at any one point during the execution of my function. This is because the `async let`s are not tied to the models as their output. If `doSomethingElse` requires the models id or fetches any eager loaded props, a crash or empty query results will almost certainly follow.
- `async let _` actually does not compile. Weirdly, Swift expects you to name your `async let`s always in order for the line to compile (which may or may not be an intentional feature in order to highlight code smells like this in the first place).

The only solution that makes sense in my mind is for `create(on:)` to return the newly created model, so it can be `await`ed upon.

```swift
async let modelA = ModelA().create(on: req.db) // modelA is async ModelA
async let modelB = ModelB().create(on: req.db) // modelB is async ModelB

doSomethingElse(with: try await [modelA, modelB])
```

**Comment by macsip** [comment]
And like this?
`let modelA = ModelA()
try await modelA.create(on: req.db)
let modelB = ModelB()
try await modelB.create(on: req.db)

doSomethingElse(with: [modelA, modelB])
`

**Comment by davdroman** [comment]
@macsip AFAIK that makes the execution sequential within the concurrent context, not parallel. So `modelB`'s creation would only start when `modelA`'s finishes. `async let` allows running both in parallel.

**Comment by davdroman** [comment]
Here's another workaround I found:

```swift
async let modelA = {
    let modelA = ModelA()
    try await modelA.create(on: req.db)
    return modelA
}()
async let modelB = {
    let modelB = ModelB()
    try await modelB.create(on: req.db)
    return modelB
}()

doSomethingElse(with: try await [modelA, modelB])
```

Still quite verbose, but it's safe.

**Comment by HowCome** [comment]
I assume that such implementation would require two trips to the database. If that is correct I would vote agains the proposal. I always can add a select request if I need it but do not want to be burdened by an unnecessary call when I do not.

**Comment by davdroman** [comment]
It's just one trip actually:

```swift
func create(on database: Database) async throws -> Self {
    try await create(on: database).get() // as usual
    return self
}
```

**Comment by HowCome** [comment]
Are you absolutely sure that the object you receive back from your code is the same as in the database ? Some of your fields could be db created (id, timestamp records or even something ran through stored procedures)

**Comment by jdmcd** [comment]
@davdroman we have this extension in our project, it works well:

```swift
public extension Model {
    func saveReturn(on database: Database) -> EventLoopFuture<Self> {
        if _$id.exists {
            return update(on: database).transform(to: self)
        } else {
            return create(on: database).transform(to: self)
        }
    }
}
```

**Comment by jdmcd** [comment]
(Need to update it for an async version still)

**Comment by gwynne** [comment]
Fluent doesn't return the model from `.create(on:)` because it explicitly updates the existing model object in-place. Since models are always reference types (classes), the reference you used to call `.create(on:)` now has updated timestamps and ID (with some caveats, see below). This was a deliberate design choice to avoid generating excess retains on model objects, though it does make things awkward in the `async/await` world. (Now, whether I _agree_ with Tanner's choice in that regard in retrospect is another question... of course, Fluent 5 will be designed for a whole different concurrency paradigm anyhow, so even if it made sense in the past, it doesn't have to anymore 😁.)

Note: If you're using anything _other_ than PostgreSQL, and your model's `@ID` property is database-generated (for example, if you use an auto-incrementing integer column instead of a UUID and a declaration like `@ID(custom: .id) var id: Int?`), the model's ID will _not_ be correctly updated by Fluent after model creation. (Fluent generates UUID-based model IDs internally, so has them available directly, and PostgreSQL has support for returning other ID types directly from an `INSERT` query, so in those cases Fluent can keep it up to date.)

**Comment by gwynne** [comment]
Oh, I meant to add: The solution @jdmcd uses is a good one. Here's an `async` version:

```swift
public extension Model {
    func saveReturn(on database: Database) async throws -> Self {
        if self._$id.exists {
            try await self.update(on: database)
        } else {
            try await self.create(on: database)
        }
        return self
    }
}
```

**Comment by davdroman** [comment]
Thanks for confirming @gwynne.

P.S: name-wise, I went with `saved(on:)` since it's shorter, and it's a pretty widely acceptable language convention to signal when a function returns vs when it mutates (`save`).

**Comment by gwynne** [comment]
@davdroman An additional belated correction: A model ID generated by the database _is_ correctly updated in the model object for MySQL databases, contrary to my previous assertion. Shout-out to @jdmcd for pointing out the error!

**Comment by davdroman** [comment]
@gwynne eager to see what's in store for Fluent 5 btw 🤩
