### ISSUE TITLE
Make plain old swift object

### ISSUE THREAD

**Issue by HowCome** [vapor/fluent-kit#466]
C# and Java ORM abandoned involved models long time ago and utilize POCO, POJO approach, which is much cleaner than involved models with db related attributes getters/setters etc.
I find it difficult to work with the current Vapor/Fluent that went the other way.
Let's say I have a logic layer which is separate from the data access layer and do some unit testing. I actually don't. That is impossible, or at least very hard. Try to create parent model in the code and assign it to the child's parent property. Very trivial task but that does not work because of all the db related code around the models
Vapor Fluent models cannot live without database so my logic layer makes no sense. It dictates sloppy programming where db queries are made directly from the api controllers, with no real unit tests
Ideally I would like to see a POSO ? objects and all db related code living outside of the models.

**Comment by 0xTim** [comment]
I think this is the same issue as Stackoverflow and the forums but the database models and database details are intrinsically linked with property wrappers. However, you can create models and manipulate them without needing a database in unit tests fine, you just need to deal with the property wrappers rather than the properties themselves
