### ISSUE TITLE
Custom index name not making it to the mysql table

### ISSUE THREAD

**Issue by ldamman** [vapor/fluent-kit#497]
I crated a new vapor project and modified the CreateTodo migration to add a unique index on title.  When I create the index with `.unique(on:name:)` (or `.foreignKey(_:references:name:)`) and pass a custom name (such as "uniqueTitle") the name in the mysql database ends up still being the default random hash instead of the name provided.

Versions...

```
MySQL version: 8.0.28
fluent version: 4.4.0
fluent-kit version: 1.23.2
fluent-mysql-driver version: 4.0.2
mysql-kit version: 4.5.0
```

CreateTodo migration diff...

```
         try await database.schema("todos")
             .id()
             .field("title", .string, .required)
+            .unique(on: "title", name: "uniqueTitle")
             .create()
```

The resulting mysql table...

```
CREATE TABLE `todos` (
  `id` varbinary(16) NOT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `0a8da0c761aa30519d7e91d0748182b6af76ca3e` (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Comment by gwynne** [comment]
Providing a constraint name does not bypass the application of the underlying driver's `SQLDialect`'s implementation of `normalizeSQLConstraint(identifier:)` at the SQLKit layer - the hash is not random; in the MySQL driver, it is the SHA-1 hash of the final name chosen (whether provided explicitly or generated by Fluent). E.g.:

```bash
$ echo -n 'uniqueTitle' | sha1sum
0a8da0c761aa30519d7e91d0748182b6af76ca3e  -
```

This was added to the MySQL driver as a workaround for Fluent commonly autogenerating constraint names (typically for foreign keys) that were longer than the allowed maximum identifier length. The only way to work around this behavior at present is to drop down to SQLKit or a raw query instead of using Fluent's schema builder; for example:

```swift
try await (database as! SQLDatabase).create(table: "todos")
    .column("id", type: .text, .primaryKey(autoIncrement: false), .notNull)
    .column("title", type: "text", .notNull)
    .unique("title", named: "uniqueTitle")
    .run()
```
