### ISSUE TITLE
Tests failing on trunk

### ISSUE THREAD

**Issue by nashysolutions** [vapor/fluent-kit#517]
<img width="263" alt="Screenshot 2022-06-25 at 06 55 48" src="https://user-images.githubusercontent.com/64097812/175760455-623f20ba-622b-4f2f-b279-1cbdb17f14c7.png">
<img width="253" alt="Screenshot 2022-06-25 at 06 56 28" src="https://user-images.githubusercontent.com/64097812/175760459-d7a0b349-bcff-42d3-afe1-a24058d7325b.png">

Steps to reproduce
1. Checkout branch main on 2b3ac0556740ea8d68f8616917daf64338d54c1b
2. Run all tests

Environment
* M1 chipset
* macOS 12.3.1
* swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
* Xcode Version 13.3 (13E113)
* Target platform - macOS

**Comment by 0xTim** [comment]
It looks like the ordering of parameters in FluentKit is not consistent on macOS - on Linux we seem to have no issues and CI is always fine.

cc @gwynne

**Comment by gwynne** [comment]
This works in CI because we set `SWIFT_DETERMINISTIC_HASHING` in the environment; it's just blind luck if it works on Linux without that. At this time, setting the env var is considered a requirement to ensure that tests pass, since fixing it in Fluent proper would introduce performance regressions (due to excess sorting), and working around it in the tests is not always practical.
