### ISSUE TITLE
Allow Decoding of a Model using the Parent Key (as found in the Table)

### ISSUE THREAD

**Issue by rnantes** [vapor/fluent-kit#98]
I should be able to use the parent key as the foreign key to the parent instead of having to use
```JSON
{
    "id": 1,
    "someJSON" : "blah blah blah",
    "owner": {
        "id": 5
     }
}

```
For example when I have model such as 
```Swift
public final class School: Model {
    public static let schema = "schools"

    @ID(key: "id")
    public var id: Int?

    @Field(key: "name")
    public var name: String

    @Field(key: "pupils")
    public var pupils: Int

    @Parent(key: "city_id")
    public var city: City
}
```
I should be able to seed school models with the following json 
```JSON
[
  {
    "id" : 300,
    "name" : "some primary school",
    "pupils" :  300,
    "city_id" : "555"
  },
  {
    "id" : 301,
    "name" : "some high school",
    "pupils" : 800,
    "city_id" : "555"
  }
]
```

**Comment by tanner0101** [comment]
Due to the way Codable works there's not really an easy way to achieve this. If the `@Parent` property has the label `city` (the swift variable name) then Codable will give it a sub-container for the value at key city. From there, `@Parent` can access any keys inside of that like the `"id"` key. It is not possible however to access the parent container from this context which would be required for accessing `"city_id"` at the top level. 

For this purpose, I think using a data-transfer object (DTO) would be the best approach. Basically create a simple struct representing the JSON, decode that struct, then use the struct to initialize your models directly.
